[workspace]
members = ["cargo:."]

[dist]
# This is the "Magic" line that fixes the panic: 
# It tells dist exactly which package name to look for
formula = "my-cool-cli"
allow-dirty = ["ci"]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
installers = ["shell", "homebrew"]
tap = "schaudhary2k/homebrew-tap"
linux-packages = ["deb"]
windows-archive = ".zip"
