[workspace]
members = ["."]

[dist]
# This ignores the integrity check for your manual .yml edits
allow-dirty = ["ci"]
# The repository for your Homebrew Formula
tap = "schaudhary2k/homebrew-tap"
# Targets for Mac, Linux, and Windows
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Explicitly tell it which installers to generate
installers = ["shell", "homebrew"]
# Tell cargo-dist to create .deb files
linux-packages = ["deb"]
# Avoids the MSI installer error on Windows
windows-archive = ".zip"
