[workspace]
# "." tells the tool the Cargo.toml is in the root, not a subdirectory
members = ["cargo:."]

[dist]
allow-dirty = ["ci"]
formula = "my-cool-cli"
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
installers = ["shell", "homebrew"]
tap = "schaudhary2k/homebrew-tap"
linux-packages = ["deb"]
windows-archive = ".zip"
